### ISSUE TITLE
Cmake issues

### ISSUE THREAD

**Issue by ipl2004** [gnuradio/gr-inspector#11]
Is this an abandoned project?, I would like to help progress this if I can. I can not find a QT4 download and qt5.8 is creating many qmake and make errors with qwtplot3d

DEBUG 1: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:38: flow control statement 'return', aborting block include/qwt3d_openglhelper.h: In function ‘const GLubyte* Qwt3D::gl_error()’:
include/qwt3d_openglhelper.h:67:31: error: ‘gluErrorString’ was not declared in this scope
   err = gluErrorString(errcode);
                               ^
include/qwt3d_openglhelper.h: In function ‘bool Qwt3D::ViewPort2World(double&, double&, double&, double, double, double)’:
include/qwt3d_openglhelper.h:104:97: error: ‘gluUnProject’ was not declared in this scope
  int res = gluUnProject(winx, winy, winz, modelMatrix, projMatrix, viewport, &objx, &objy, &objz);
                                                                                                 ^
include/qwt3d_openglhelper.h: In function ‘bool Qwt3D::World2ViewPort(double&, double&, double&, double, double, double)’:
include/qwt3d_openglhelper.h:120:95: error: ‘gluProject’ was not declared in this scope
  int res = gluProject(objx, objy, objz, modelMatrix, projMatrix, viewport, &winx, &winy, &winz);
                                                                                               ^
Reaping losing child 0x1642350 PID 30241 
Makefile:519: recipe for target 'tmp/qwt3d_axis.o' failed
make: *** [tmp/qwt3d_axis.o] Error 1

**Comment by chrisruk** [comment]
Hi,

I'm not sure what distribution you're using, but in Arch, I have qt4 installed via pacman along with qwtplot3d.

**Comment by ipl2004** [comment]
Hi, 
I am using Ubuntu 16.04, I installed the



    GNU Radio <installed>
    gr-analog, gr-blocks, gr-channel, gr-filter
    QT4 < I do actually have the QT4 and QT5.8>
    QWT 6.1.0  <installed ok>
    QwtPlot3D < qmake and make errors> 
    TensorFlow 0.12 (pip installation - you need the version for Python 2.7) <installed> 

I installed qwt6.1.0 using QT5 I am wondering if there lies the problem.

Ian

**Comment by chrisruk** [comment]
Try doing:
apt-cache search qwtplot3d

I don't use ubuntu on the desktop but can see something like 'libqwtplot3d-qt4-0v5' exists on my server.

**Comment by ipl2004** [comment]
recompiled all with QT4 (qmake, make install) 

QWTPlot3D is still unhappy 

g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIC -DGL2PS_HAVE_ZLIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iinclude -I/usr/X11R6/include -Itmp -o tmp/qwt3d_axis.o src/qwt3d_axis.cpp
In file included from include/qwt3d_types.h:26:0,
                 from include/qwt3d_drawable.h:7,
                 from include/qwt3d_label.h:10,
                 from include/qwt3d_axis.h:5,
                 from src/qwt3d_axis.cpp:1:
include/qwt3d_openglhelper.h: In function ‘const GLubyte* Qwt3D::gl_error()’:
include/qwt3d_openglhelper.h:67:31: error: ‘gluErrorString’ was not declared in this scope
   err = gluErrorString(errcode);
                               ^
include/qwt3d_openglhelper.h: In function ‘bool Qwt3D::ViewPort2World(double&, double&, double&, double, double, double)’:
include/qwt3d_openglhelper.h:104:97: error: ‘gluUnProject’ was not declared in this scope
  int res = gluUnProject(winx, winy, winz, modelMatrix, projMatrix, viewport, &objx, &objy, &objz);
                                                                                                 ^
include/qwt3d_openglhelper.h: In function ‘bool Qwt3D::World2ViewPort(double&, double&, double&, double, double, double)’:
include/qwt3d_openglhelper.h:120:95: error: ‘gluProject’ was not declared in this scope
  int res = gluProject(objx, objy, objz, modelMatrix, projMatrix, viewport, &winx, &winy, &winz);

Ian

**Comment by ipl2004** [comment]
ian@ian-OptiPlex-790:~/Downloads/qwtplot3d$ apt-cache search qwtplot3d
libqwtplot3d-doc - 3D plotting library based on Qt/OpenGL (documentation)
libqwtplot3d-qt4-0v5 - 3D plotting library based on Qt4/OpenGL (runtime)
libqwtplot3d-qt4-dev - 3D plotting library based on Qt4/OpenGL (development)
libqwtplot3d-qt5-0 - 3D plotting library based on Qt5/OpenGL (runtime)
libqwtplot3d-qt5-dev - 3D plotting library based on Qt5/OpenGL (development)
python-qwt3d-doc - Documentation for the Python-qwt3d library
python-qwt3d-qt4 - Python bindings of the QwtPlot3D library

**Comment by chrisruk** [comment]
Try and install:

libqwtplot3d-qt4-0v5 - 3D plotting library based on Qt4/OpenGL (runtime)
libqwtplot3d-qt4-dev - 3D plotting library based on Qt4/OpenGL (development)

**Comment by ipl2004** [comment]
Hi Chris, thanks for the help. The cmake files have been updated, I need to do some editing. I did not see the changes.

Ian

**Comment by ipl2004** [comment]
Again many thanks for your help Chris.

Ian

**Comment by sbmueller** [comment]
@ipl2004 has the issue been resolved? If so, could you please close this thread? Thanks!

**Comment by ipl2004** [comment]
Hi, yes the issue is solved
adding the following libs: 
libqwtplot3d-qt4-0v5 - 3D plotting library based on Qt4/OpenGL (runtime)
libqwtplot3d-qt4-dev - 3D plotting library based on Qt4/OpenGL (development)

and qmake/make with QT4 solved the problems.

**Comment by ajeyaajeya** [comment]
I am facing the same error.
Does qwtplot3d-qt4 come installed with the standard sudo apt-get install qt4-default?
How do I install qwtplot3d-qt4?

**Comment by sbmueller** [comment]
@ajeyaajeya the packages are called, as stated by @ipl2004 
> libqwtplot3d-qt4-0v5 - 3D plotting library based on Qt4/OpenGL (runtime)
> libqwtplot3d-qt4-dev - 3D plotting library based on Qt4/OpenGL (development)

and need to be installed explicitly.

**Comment by alphapats** [comment]
Error while cmake of maint-3.7 branch

Error while installing "libqwtplot3d-qt4-dev " 
Error Msg: "Package libqwtplot3d-qt4-dev is not available, but is referred to by another package"
Fwg packages are already installed: 
libqwtplot3d-qt5-0 is already the newest version (0.2.7+svn191+gcc7-2).
libqwtplot3d-qt5-dev is already the newest version (0.2.7+svn191+gcc7-2).
