### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signal_detector_cvf'

### ISSUE THREAD

**Issue by ziyuanjun** [gnuradio/gr-inspector#14]
No one `.grc` in `examples/ ` can run. Take signal_detection.grc as an example, after I run the .grc file, these messages come out:

> ...
> File "signal_detection.py", line 74, in __init__
>     self.inspector_signal_detector_cvf_0 = inspector.signal_detector_cvf(samp_rate, 4096, firdes.WIN_BLACKMAN_hARRIS,
> AttributeError: 'module' object has no attribute 'signal_detector_cvf'

**Comment by sbmueller** [comment]
This message just means gr-inspector is not installed correctly. Please follow the installation instructions and basic GNU Radio tutorials to troubleshoot.

**Comment by jackalak** [comment]
Works best if you do 
Pybombs install gr-inpector
Much more difficult doing the steps yourself

**Comment by ziyuanjun** [comment]
Thank you very much! I reinstall `gnuradio` and `gr-inpector` using Pybombs. Now the AttributeError is fixed.
