### ISSUE TITLE
How to get a Graph file for TensorFlow AMC Model?

### ISSUE THREAD

**Issue by ziyuanjun** [gnuradio/gr-inspector#15]
It seems that the amc_cnn.grc file in examples directory cannot run directly. 
The Graph file for TensorFlow AMC Model,` /tmp/cnn/000001`, is needed. 

I'm a novice. Could any good guy show me some clue to start to use tensorflow and gr-inspector.
I'll appreciate that.

**Comment by sbmueller** [comment]
Please follow the documentation at http://gnuradio.github.io/gr-inspector/index.html#models

**Comment by mbr0wn** [comment]
No issue here, please move to mailing list.

**Comment by Infiltra** [comment]
Hey, Muller that link is not working. Is there another resource?

**Comment by sbmueller** [comment]
The link to the documentation covers only the current version. AMC features were implemented by @chrisruk and unfortunately not ported to GR 3.8 or later. You can look at the original documentation in the `maint-3.7` branch: https://github.com/gnuradio/gr-inspector/blob/maint-3.7/docs/doxygen/other/main_page.dox#L35

**Comment by Infiltra** [comment]
Thanks Sebastian!

**Comment by alphafox02** [comment]
@bkerler aby 

> The link to the documentation covers only the current version. AMC features were implemented by @chrisruk and unfortunately not ported to GR 3.8 or later. You can look at the original documentation in the `maint-3.7` branch: https://github.com/gnuradio/gr-inspector/blob/maint-3.7/docs/doxygen/other/main_page.dox#L35

@bkerler any chance for 3.10 port?
