### ISSUE TITLE
ofdm_bouzegzi_c_impl.cc  Error while installing

### ISSUE THREAD

**Issue by steven-bloom** [gnuradio/gr-inspector#17]
Hello to everyone! :-)
I would like to install your tool, but facing following Problem.
Could anybody please help me.

![screenshot from 2017-11-01 18-27-09](https://user-images.githubusercontent.com/30798903/32287830-51e056ec-bf32-11e7-93c8-6e282ff4706f.png)
Any help would be greatly appreciated

**Comment by sbmueller** [comment]
Hello Steven, what you are describing is not a bug or issue, but an explicit problem with using the software on your machine. GitHub issues is not the right place for this, please use the mailing list specified in the README. If you open a thread there, we need much more information like complete cmake and make output, installed cmake/gcc/gnuradio versions, distro version, etc. Thanks.
