### ISSUE TITLE
QT GUI Inspector Sink template error

### ISSUE THREAD

**Issue by karel** [gnuradio/gr-inspector#20]
QT GUI Inspector Sink is not working with [GNURadio 3.7.12.0](https://github.com/gnuradio/gnuradio/releases/tag/v3.7.12.0).

```
Generating: '/home/karel/build/gr-inspector/examples/signal_detection.py'

Executing: /usr/bin/python2 -u /home/karel/build/gr-inspector/examples/signal_detection.py

  File "/home/karel/build/gr-inspector/examples/signal_detection.py", line 77
    self.inspector_qtgui_sink_vf_0 = Template error: #set $win = 'self._%s_win'%$id
                                                  ^
SyntaxError: invalid syntax

>>> Done (return code 1)
```

**Comment by marcusmueller** [comment]
does https://github.com/gnuradio/gnuradio/commit/20ef863e86289107bc4c6cc375edd5890a363694 help here?

**Comment by karel** [comment]
@marcusmueller unfortunately it does not. Latest GNURadio built with https://github.com/gnuradio/gnuradio/commit/d19965e42d12bba66e39fd20794c69c69c48b31f applied and building gr-inspector without the proposed fix in #21 results in the exact same error as stated above.

**Comment by KiLLeR-R** [comment]
Tried #21...but unfortunately a new error popped up-

 **File "/usr/local/lib/python2.7/dist-packages/gnuradio/qtgui/qtgui_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_qtgui_swig', fp, pathname, description)
ImportError: libqwt-qt4.so.5: cannot open shared object file: No such file or directory**

**Comment by marcusmueller** [comment]
That's a linker error. There's something else wrong.

**Comment by KiLLeR-R** [comment]
![cmake_output](https://user-images.githubusercontent.com/38506428/38952066-06c41b20-4368-11e8-88a0-595002a1dc11.png)
![cmake_output_2](https://user-images.githubusercontent.com/38506428/38952067-06fdb5ba-4368-11e8-8171-a77bea2e8c35.png)
![make_output](https://user-images.githubusercontent.com/38506428/38952069-072b390e-4368-11e8-81dc-0dee6d83f110.png)
Attaching output of my cmake and make...
make install ran without any error..
im kinda lost regarding my error.Any advice will b helpful :)

**Comment by KiLLeR-R** [comment]
Upgrading gnuradio to latest version and #21 solved all the mentioned problems.

**Comment by sbmueller** [comment]
This should be solved since GNU Radio 3.7.13.3 (https://github.com/gnuradio/gnuradio/commit/dbdd204ccd3e4d174f4390bcd0948f33f1a8bf0d)

**Comment by catalinalb** [comment]
I have the same error as described on top: 
 self.fosphor_qt_sink_c_0 = Template error: #set $win = 'self._%s_win'%$id
                                            ^
SyntaxError: invalid syntax

I still didn't understand how to fix it. Can someone explain in small steps?

Thank you

**Comment by sbmueller** [comment]
@catalinalb Which OS are you running? Which version of GNU Radio are you running and how did you install it?

**Comment by catalinalb** [comment]
Ubuntu 18.04  gnuradio 3.7
Installation with pybombs

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sbmueller** [comment]
Please make sure you have GNU Radio 3.7.13.3 or later installed. E.g. reinstalling the package `gnuradio37` should work.
