### ISSUE TITLE
Сompatibility with GNURadio 3.8.0

### ISSUE THREAD

**Issue by geosphere** [gnuradio/gr-inspector#31]
Hello! Any chances to update the module?

**Comment by sbmueller** [comment]
Updating gr-inspector to GR 3.8 is on my todo list, however I'm having trouble finding enough time for this and don't have regular access to a linux machine. Help is definitely welcome :).

**Comment by sbmueller** [comment]
I have started a `dev_3.8` branch for this. The strategy I'm pursuing is to create a "new" OOT with same name, and incorporate the source code into that module.

**Comment by cwalde-bluecom** [comment]
Hello, have there been any updates? I'm trying to update as well and would like to help if possible. My plan of attack is currently updating all the versions necessary.

**Comment by sbmueller** [comment]
Yes, basically I'm digging my way through the codebase and CMake. cmake now runs through without complaints :grimacing: . I regularly push my work to  `dev_3.8`.

**Comment by cwalde-bluecom** [comment]
Okay, I cloned the dev_3.8 repository and will start from here. I am new to Linux in general, so I'll help out where I can!

**Comment by jaarestad-bluecom** [comment]
I am getting errors related such as the following: 
<pre>In file included from <b>/home/jim/GitLab/GRC/OOT/gr-inspector/build/lib/moc_inspector_form.cpp:9:0</b>:
<b>/home/jim/GitLab/GRC/OOT/gr-inspector/build/lib/../../lib/inspector_form.h:127:7:</b> <font color="#EF2929"><b>error: </b></font>‘<b>QGridLayout</b>’ does not name a type; did you mean ‘<b>QGlyphLayout</b>’?</pre>

These errors are similar (if not identical) to errors I was getting when trying to develop a small test app using Qt5 on another system.  Any further progress on this?  

Jim

**Comment by sbmueller** [comment]
@jaarestad-bluecom the branch is not yet usable. It's so far only used to store the intermediate results of the porting.

**Comment by sbmueller** [comment]
gr-inspector is now compatible with GNU Radio 3.8. There is a `master` branch which will keep up compatibility with GNU Radio's master as well as a `maint-3.8` branch for compatibility with GNU Radio 3.8.

**Comment by JJYjackson** [comment]
Hello! Can the Graph file of Tensorflow AMC Model be provided？ I will be deeply grateful！
![image](https://user-images.githubusercontent.com/65533171/86551018-806e9b80-bf76-11ea-8079-bdb29ca6b9fb.png)

**Comment by JJYjackson** [comment]
would be grateful if you could possibly help me with this.

**Comment by JJYjackson** [comment]
Can you provide the graph file of tensorflow AMC model？would be grateful if you could possibly help me with this.
![image](https://user-images.githubusercontent.com/65533171/86551820-caf11780-bf78-11ea-880b-8c979b1fbc8a.png)

**Comment by sbmueller** [comment]
@JJYjackson this issue is not the right place to ask, however try this: https://github.com/chrisruk/models.

**Comment by Infiltra** [comment]
@sbmueller with regards to the vis3d blocks porting to 3.8, I have done some changes and I end up with the error in the image for all blocks. Any ideas on how to move forward.
![image](https://user-images.githubusercontent.com/17112788/126049577-b24d7a4d-7cb1-4f61-8088-748adf9c557d.png)
