### ISSUE TITLE
gr-inspector will work on gnu radio version 3.10.0

### ISSUE THREAD

**Issue by Ayush-IND** [gnuradio/gr-inspector#37]
hello,
I am installing gr- inspector, my current gnu radio version is 3.10.0 as i have recently installed.
I am getting cmake error while installing.
CMake Error at swig/CMakeLists.txt:37 (include):
  include could not find load file:

    GrSwig

CMake Error at swig/CMakeLists.txt:54 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE".

-- Configuring incomplete, errors occurred!

please suggest.

regards
ayush

**Comment by davew723** [comment]
Did you find a solution for this problem?
