### ISSUE TITLE
Problem with latest Qt/Qwt

### ISSUE THREAD

**Issue by wkazubski** [gnuradio/gr-inspector#40]
I have problem with building gr-ispector on openSUSE Tumbleweed with latest version of Qt 5.15.2 and Qwt 6.2.0:
...
[   77s] /home/abuild/rpmbuild/BUILD/gr-inspector/lib/inspector_form.cc: In constructor 'gr::inspector::inspector_form::inspector_form(int, std::vector<double>*, std::vector<std::vector<float> >*, bool*, gr::msg_queue*, int*, QWidget*)':
[   77s] /home/abuild/rpmbuild/BUILD/gr-inspector/lib/inspector_form.cc:82:49: error: invalid use of incomplete type 'class QwtText'
[   77s]    82 |     d_plot->setTitle(QwtText(label_title.c_str()));
[   77s]       |                                                 ^
[   77s] In file included from /usr/include/qt5/qwt6/qwt_plot_dict.h:14,
[   77s]                  from /usr/include/qt5/qwt6/qwt_plot.h:15,
[   77s]                  from /home/abuild/rpmbuild/BUILD/gr-inspector/lib/../include/inspector/inspector_form.h:31,
[   77s]                  from /home/abuild/rpmbuild/BUILD/gr-inspector/lib/inspector_form.cc:21:
[   77s] /usr/include/qt5/qwt6/qwt_plot_item.h:20:7: note: forward declaration of 'class QwtText'
[   77s]    20 | class QwtText;
[   77s]       |       ^~~~~~~
...

**Comment by dkozel** [comment]
I think this is now solved in the latest updates so am closing the issue. I hope you found a solution at the time.
