### ISSUE TITLE
CMake error during installation

### ISSUE THREAD

**Issue by Gitoffomalawn** [gnuradio/gr-inspector#41]
Hi,

I'm running GNU Radio 3.9, and am trying to install gr-inspector. I have followed the install steps detailed in the repo to the letter.

I keep running into an error with cmake:
```
CMake Error at swig/CMakeLists.txt:37 (include):
  include could not find requested file:

    GrSwig


CMake Error at swig/CMakeLists.txt:54 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE".
```

SWIG is installed on my system, currently version 4.0.2. A little bit of googling indicates that SWIG may not be compatible with GNU Radio beyond version 3.8. However, this is a problem for me, as I need to use the current version (3.9).

Is there a possible workaround, or maybe some additional information available regarding this issue?

**Comment by wkazubski** [comment]
This is because gr-inspector is not ported to GR-3.9 yet. There are no significant changes since porting to 3.8.

**Comment by Gitoffomalawn** [comment]
Thanks for the feedback. Does this mean gr-inspector only works on GNU Radio up to version 3.8, and a downgrade to that version is my only option?

**Comment by Gitoffomalawn** [comment]
Update: downgrading all necessary packages and their dependencies has solved the issues I was getting with `cmake ..`. However, now when executing `make -j4` I'm getting a bunch of "not defined in this scope" errors.

**Comment by greyhat94** [comment]
I'm using gnuradio 3.10.3 and gr-gsm. I'm following the instructions on this page: https://osmocom.org/projects/gr-gsm/wiki/Installation
I got the error above mentioned by the OP. How can I fix it? You said I need to downgrade, but I don't know how to do it.

**Comment by greyhat94** [comment]
> Update: downgrading all necessary packages and their dependencies has solved the issues I was getting with `cmake ..`. However, now when executing `make -j4` I'm getting a bunch of "not defined in this scope" errors.

I'm using Kali Linux and Gnuradio 3.10.3. How can I fix this error? I don't know how to downgrande all packages and dependecies. I'm talking about the error concerning the missing swig file.

**Comment by dkozel** [comment]
@greyhat94.  the code is now updated to support GNU Radio 3.10. Please switch to the maint-3.10 branch and rebuild.
