### ISSUE TITLE
maint-3.10 branch doesn't actually appear to be GR3.10 compatible? 

### ISSUE THREAD

**Issue by ion-concepts** [gnuradio/gr-inspector#49]
`maint-3.10` and `main` fail to build against GR 3.10.8 because of use of the __GR_VLA macro which was removed from GR3.10 @a2f39b26239784bf6b01e3c289fb0f90041167ce

**Comment by marcusmueller** [comment]
yep, stumbled across the same yesterday on stage. oops. Fixed that in a PR. Sorry, @ion-concepts !

**Comment by marcusmueller** [comment]
can you try #52 , @ion-concepts ? Note that I tried nothing but running the unit tests after these fixes.

**Comment by ion-concepts** [comment]
Confirm I can now build this against current GR maint-3.10. 
One quirk, I have `libspdlog-dev/focal,now 1:1.5.0-1 amd64 [installed]` and had to make the following change:
```diff --git a/lib/ofdm_bouzegzi_c_impl.cc b/lib/ofdm_bouzegzi_c_impl.cc
index e299956..5384a7d 100644
--- a/lib/ofdm_bouzegzi_c_impl.cc
+++ b/lib/ofdm_bouzegzi_c_impl.cc
@@ -26,7 +26,7 @@
 #include <gnuradio/gr_complex.h>
 #include <gnuradio/io_signature.h>
 #include <gnuradio/logger.h>
-#include <spdlog/fmt/ranges.h>
+#include <spdlog/fmt/bundled/ranges.h>
 #include <volk/volk.h>
 #include <volk/volk_alloc.hh>
 #include <complex>

**Comment by marcusmueller** [comment]
Oh nice! Thanks! 

Thankfully, under C++17, the preprocessors can check for existence if headers, so I think I can make that portable! Awesome!
