### ISSUE TITLE
Compile error on OS X 

### ISSUE THREAD

**Issue by mehdideveloper** [gnuradio/gr-inspector#5]
Hi
I cloned from git and running "cmake" gives no error, but "make" returned an error while building:

> [ 29%] Building CXX object lib/CMakeFiles/gnuradio-inspector.dir/ofdm_bouzegzi_c_impl.cc.o
> /Users/abc/Source/gr-inspector/lib/ofdm_bouzegzi_c_impl.cc:166:21: error:
>       variable length array of non-POD element type 'gr_complex'
>       (aka 'complex<float>')
>       gr_complex pre[M];
>                     ^
> 1 error generated.
> make[2]: **\* [lib/CMakeFiles/gnuradio-inspector.dir/ofdm_bouzegzi_c_impl.cc.o] Error 1
> make[1]: **\* [lib/CMakeFiles/gnuradio-inspector.dir/all] Error 2
> make: **\* [all] Error 2

Any ideas?
Thanks

Some info:
OS X 10.11.6
Boost 1.60.0
QWT: 6.1.2
gnuradio-runtime, version 3.7.9.1

**Comment by sbmueller** [comment]
Hi @mehdideveloper . I recommend using Linux since OS X tends to complicate things. If this is not possible for you, you can try the following:
1) The error seems like an compiler error. Since OS X uses it's own clang instead of gcc, you could try to manually force gcc as compiler. Compiling with gcc under Linux works fine.
2) The mentioned file is deprecated, but left in the repo because there is a fancy algorithm implemented and hopefully someone will make use of it one day. You can try deleting it (along with all the CMake changes).

**Comment by mehdideveloper** [comment]
Thanks for the quick reply.
I changed 3 lines in ofdm_bouzegzi_c_impl.cc and  ofdm_zkf_c_impl.cc and then I could successfully compile it.
When I installed it and ran the "gnuradio-companion", it crashes!

Some lines consisting the crash info:

> Warning: restarting the docstring loader (crashed while loading 'inspector_ofdm_synchronizer_cc')
> 
> > > > Done
> > > > Warning: restarting the docstring loader (crashed while loading 'inspector_ofdm_zkf_c')
> > > > Warning: restarting the docstring loader (crashed while loading 'inspector_qtgui_sink_vf')
> > > > Warning: restarting the docstring loader (crashed while loading 'inspector_signal_detector_cvf')
> > > > Warning: restarting the docstring loader (crashed while loading 'inspector_signal_extractor_c')
> > > > Warning: docstring loader crashed too often

It may be caused by incompatible Python and/or other libraries (like qt)
I will try to fix it, but your ideas/suggestions are appreciated.

**Comment by sbmueller** [comment]
It seems like GRC has now trouble to get the python docstrings from the GR blocks. You can try importing inspector into a python interpreter and then trying to print `[blockname].__doc__`. This is where the docstring lives.

**Comment by sbmueller** [comment]
I'll close this due to inactivity.

**Comment by perks** [comment]
@mehdideveloper Which lines did you change to get it to compile on OSX?

**Comment by mehdideveloper** [comment]
@perks 
Those 3 lines are creating new arrays with variables as the size parameter. I replaced them with the equivalent version, using the "new" operator (allocating dynamically)
I found them based on the error details provided by the compiler.
The first one: ofdm_bouzegzi_c_impl.cc:166, replaced with:
`gr_complex *pre = new gr_complex[M];`
Second one: ofdm_zkf_c_impl.cc:78  , replaced with:
`gr_complex *Rxx = new gr_complex[len];`
And the last one:  ofdm_zkf_c_impl.cc (line 100 or so), replaced with:
`gr_complex *corr_temp = new gr_complex[len];`

I also used "delete []" operator after I'm done with these in the code.

**Comment by perks** [comment]
@mehdideveloper thanks for replying! Might get around to messing with it on OSX later.

**Comment by cn0xroot** [comment]
Compile error on OS X too:
Could NOT find Qt4 (missing: QT_QWTPLOT3D_INCLUDE_DIR QT_QWTPLOT3D_LIBRARY)
  (found suitable version "4.8.7", minimum required is "4.2.0")

```
 cmake ..
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- The C compiler identification is AppleClang 8.0.0.8000038
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2")
-- Found PythonInterp: /usr/local/bin/python2 (found suitable version "2.7.10", minimum required is "2")
--
-- Python checking for PyQt4
-- Python checking for PyQt4 - found
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cppunit'
--   Found cppunit, version 1.13.2
-- Found CPPUNIT: /opt/local/lib/libcppunit.dylib
-- Found Doxygen: /opt/local/bin/doxygen (found version "1.8.10")
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - found
CMake Error at /opt/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Qt4 (missing: QT_QWTPLOT3D_INCLUDE_DIR QT_QWTPLOT3D_LIBRARY)
  (found suitable version "4.8.7", minimum required is "4.2.0")
Call Stack (most recent call first):
  /opt/local/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.7/Modules/FindQt4.cmake:1323 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:152 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/Good-Soon/gr-inspector/build/CMakeFiles/CMakeOutput.log".
See also "/Users/Good-Soon/gr-inspector/build/CMakeFiles/CMakeError.log".
```

**Comment by jackalak** [comment]
You need libqt4. 
Also possible you have qt5, but the older qt4 is needed.   Its also possible the library is not in your library path or has a broken link. In Ubuntu, using pybombs takes care of this for you. Maybe that works in osx

**Comment by ajeyaajeya** [comment]
Having the same problem

**Comment by michaelld** [comment]
If you're using Qt4 from MacPorts, then you'll want to do something like:
```
QTDIR=/opt/local/libexec/qt4 cmake ..
```
in order for the MP Qt4 to be found. We install it into a nonstandard location to allow Qt4 and Qt5 to be installable at the same time.

**Comment by ajeyaajeya** [comment]
I am using Ubuntu and still getting error. I do not know how to solve this.

**Comment by michaelld** [comment]
@ajeyaajeya Please send an email to "support@ettus.com" with your queries; please include info such as your OS and how you're trying to build "gr-inspector" and the actual build log from "make VERBOSE=ON".

**Comment by michaelld** [comment]
This issue is closed and is related to issues on OSX. Issues on Linux will generally be different.
