### ISSUE TITLE
Error while installing gr-inspector

### ISSUE THREAD

**Issue by alphapats** [gnuradio/gr-inspector#50]
I am trying to install gr-inspector (maint gnuradio 3.7 branch). I am getting following error during cmake ../ :-
`
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Qt4 (missing: QT_QWTPLOT3D_LIBRARY) (found suitable version
  "4.8.7", minimum required is "4.2.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.25/Modules/FindQt4.cmake:1328 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:152 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/user/Documents/gr-inspector/build/CMakeFiles/CMakeOutput.log".
See also "/home/user/Documents/gr-inspector/build/CMakeFiles/CMakeError.log".
`
I am using ubuntu 18 and GNU Radio Companion 3.7.13.4.

**Comment by marcusmueller** [comment]
maint-3.7 is unmainted and unmaintainable on modern, Python2-free machines. We'll sadly won't fix any bugs on that.
