### ISSUE TITLE
After compile and install, could not run with ModuleNotFoundError

### ISSUE THREAD

**Issue by andymatos** [gnuradio/gr-inspector#53]
Hi, all. I follow the install guide in readme file. I checkout the maint-3.8 branch, the building and install, everything works fine.
But when I start to use the module in GNU Radio companion, it finally ends with ModuleNotFoundError: No module named 'inspector'
Am I missing anything during installation?
Here is the error screen
![Screenshot from 2024-09-01 02-06-51](https://github.com/user-attachments/assets/ad630726-4767-4d94-9829-b714b4380d09)

**Comment by marcusmueller** [comment]
That's an installation error on your end (should be a FAQ entry on the GNU Radio wiki with your error message :) ); also, maint-3.8 will no longer be supported, I'm afraid.
